### PR TITLE
Fix equality comparison for types (Fixes #749)

### LINKED ISSUE #749: Static calls on e.g float.__eq__/float.__ne__ fails
Hi,
I have some code where I need to pass the method ´float.___eq__´_ as a callback, but it fails in Brython.
Minimum code to reproduce it is:

`assert float.__eq__(1.5, 1.5)` or
`assert not float.__ne__(1.5, 1.5)`

It also applies for int.
The other operators, works as expected

### PR DESCRIPTION
**Pull request by jonathanverner**
The `__eq__` method of a class should not be used when comparing two
classes (it should only be used when comparing instances of the class).
This patch replaces instances of

```javascript
_b_.getattr(objA, '__eq__')(objB)
```

which were used to test equality of `objA`, `objB` with

```javascript
$B.rich_comp("__eq__", objA, objB)
```

which is modified to properly handle the case when `objA` and `objB` are
types.

### CODE REVIEW

File: www/src/py_utils.js [hunk 1]
```diff
@@ -1347,6 +1347,27 @@ $B.rich_comp = function(op, x, y){
         }
     }
     var res, rev_op, compared = false
+
+    if(x.__class__ && x.__class__.$factory === $B.$type.$factory && y.__class__ && y.__class__.$factory === $B.$type.$factory) {
+        if ( op == '__eq__') {
+            return (x === y || x.$factory === y || y.$factory === x)
```
Comment (jonathanverner) [inline www/src/py_utils.js]: I am not exactly sure why `x === y` is not enough, but without this the descriptor tests fail. What is the correct way to test if two types are equal?

**Comment by jonathanverner** [comment]
@PierreQuentel I'd be happy if you could go over the changes. In particular I am afraid of the performance impact of the changes and perhaps there's a better way to fix Issue #749. Also, I am a bit puzzled by the CI failing. When I run it locally, everything works perfectly fine. Also in my fork the tests pass...

**Comment by PierreQuentel** [comment]
Many thanks for the fix, it was not an easy one !

The code you were not sure about in __py_utils.js__ was needed because of a bug in the descriptors implementation. I have fixed it in commit 8994ef59a87b72fd30d7b0a14ff5f81d8ea6772a and simplified the code in `$B.rich_comp`.
